SMALL = ['ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'Car', 'CBF',
         'CinCECGTorso', 'Coffee',
         'DiatomSizeReduction',
         'DistalPhalanxOutlineAgeGroup', 'DistalPhalanxTW',
         'Earthquakes', 'ECG200', 'ECGFiveDays', 'FaceFour',
         'FacesUCR', 'Fish', 'GunPoint', 'Ham',
         'Haptics', 'Herring', 'InlineSkate', 'ItalyPowerDemand',
         'Lightning2', 'Lightning7', 'Mallat', 'Meat', 'MiddlePhalanxTW',
         'MiddlePhalanxOutlineAgeGroup',
         'MoteStrain', 'OliveOil',
         'OSULeaf', 'Plane',
         'ShapeletSim', 'SonyAIBORobotSurface1',
         'SonyAIBORobotSurface2', 'Symbols',
         'ToeSegmentation1', 'ToeSegmentation2', 'Trace', 'TwoLeadECG',
         'Wine', 'Worms', 'WormsTwoClass']
LARGE = ['FiftyWords', 'Adiac', 'ChlorineConcentration', 'Computers', 'CricketX', 'CricketY', 'CricketZ',
         'DistalPhalanxOutlineCorrect',
         'ECG5000', 'ElectricDevices', 'FaceAll', 'FordA', 'FordB', 'HandOutlines', 'InsectWingbeatSound',
         'LargeKitchenAppliances', 'MedicalImages',
         'MiddlePhalanxOutlineCorrect', 'NonInvasiveFetalECGThorax1', 'NonInvasiveFetalECGThorax2',
         'PhalangesOutlinesCorrect', 'Phoneme', 'ProximalPhalanxOutlineAgeGroup',
         'ProximalPhalanxOutlineCorrect', 'ProximalPhalanxTW', 'RefrigerationDevices', 'ScreenType',
         'ShapesAll', 'SmallKitchenAppliances',
         'StarLightCurves', 'Strawberry', 'SwedishLeaf', 'SyntheticControl', 'TwoPatterns',
         'UWaveGestureLibraryAll', 'UWaveGestureLibraryX', 'UWaveGestureLibraryY',
         'UWaveGestureLibraryZ', 'Wafer', 'WordSynonyms', 'Yoga'
         ]

TOTAL85 = ['ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'Car', 'CBF',
           'CinCECGTorso', 'Coffee',
           'DiatomSizeReduction',
           'DistalPhalanxOutlineAgeGroup', 'DistalPhalanxTW',
           'Earthquakes', 'ECG200', 'ECGFiveDays', 'FaceFour',
           'FacesUCR', 'Fish', 'GunPoint', 'Ham',
           'Haptics', 'Herring', 'InlineSkate', 'ItalyPowerDemand',
           'Lightning2', 'Lightning7', 'Mallat', 'Meat', 'MiddlePhalanxTW',
           'MiddlePhalanxOutlineAgeGroup',
           'MoteStrain', 'OliveOil',
           'OSULeaf', 'Plane',
           'ShapeletSim', 'SonyAIBORobotSurface1',
           'SonyAIBORobotSurface2', 'Symbols',
           'ToeSegmentation1', 'ToeSegmentation2', 'Trace', 'TwoLeadECG',
           'Wine', 'Worms', 'WormsTwoClass', 'FiftyWords', 'Adiac', 'ChlorineConcentration', 'Computers', 'CricketX',
           'CricketY', 'CricketZ',
           'DistalPhalanxOutlineCorrect',
           'ECG5000', 'ElectricDevices', 'FaceAll', 'FordA', 'FordB', 'HandOutlines', 'InsectWingbeatSound',
           'LargeKitchenAppliances', 'MedicalImages',
           'MiddlePhalanxOutlineCorrect', 'NonInvasiveFetalECGThorax1', 'NonInvasiveFetalECGThorax2',
           'PhalangesOutlinesCorrect', 'Phoneme', 'ProximalPhalanxOutlineAgeGroup',
           'ProximalPhalanxOutlineCorrect', 'ProximalPhalanxTW', 'RefrigerationDevices', 'ScreenType',
           'ShapesAll', 'SmallKitchenAppliances',
           'StarLightCurves', 'Strawberry', 'SwedishLeaf', 'SyntheticControl', 'TwoPatterns',
           'UWaveGestureLibraryAll', 'UWaveGestureLibraryX', 'UWaveGestureLibraryY',
           'UWaveGestureLibraryZ', 'Wafer', 'WordSynonyms', 'Yoga']
UNIVARIATE_DATASET_NAMES_2018 = ['ACSF1', 'Adiac', 'AllGestureWiimoteX', 'AllGestureWiimoteY', 'AllGestureWiimoteZ',
                                 'ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'BME', 'Car', 'CBF', 'Chinatown',
                                 'ChlorineConcentration', 'CinCECGTorso', 'Coffee', 'Computers', 'CricketX',
                                 'CricketY', 'CricketZ', 'Crop', 'DiatomSizeReduction',
                                 'DistalPhalanxOutlineAgeGroup', 'DistalPhalanxOutlineCorrect', 'DistalPhalanxTW',
                                 'DodgerLoopDay', 'DodgerLoopGame', 'DodgerLoopWeekend', 'Earthquakes', 'ECG200',
                                 'ECG5000', 'ECGFiveDays', 'ElectricDevices', 'EOGHorizontalSignal',
                                 'EOGVerticalSignal', 'EthanolLevel', 'FaceAll', 'FaceFour', 'FacesUCR',
                                 'FiftyWords', 'Fish', 'FordA', 'FordB', 'FreezerRegularTrain',
                                 'FreezerSmallTrain', 'Fungi', 'GestureMidAirD1', 'GestureMidAirD2',
                                 'GestureMidAirD3', 'GesturePebbleZ1', 'GesturePebbleZ2', 'GunPoint',
                                 'GunPointAgeSpan', 'GunPointMaleVersusFemale', 'GunPointOldVersusYoung',
                                 'Ham', 'HandOutlines', 'Haptics', 'Herring', 'HouseTwenty', 'InlineSkate',
                                 'InsectEPGRegularTrain', 'InsectEPGSmallTrain', 'InsectWingbeatSound',
                                 'ItalyPowerDemand', 'LargeKitchenAppliances', 'Lightning2', 'Lightning7',
                                 'Mallat', 'Meat', 'MedicalImages', 'MelbournePedestrian',
                                 'MiddlePhalanxOutlineAgeGroup', 'MiddlePhalanxOutlineCorrect',
                                 'MiddlePhalanxTW', 'MixedShapesRegularTrain', 'MixedShapesSmallTrain',
                                 'MoteStrain', 'NonInvasiveFetalECGThorax1', 'NonInvasiveFetalECGThorax2',
                                 'OliveOil', 'OSULeaf', 'PhalangesOutlinesCorrect', 'Phoneme',
                                 'PickupGestureWiimoteZ', 'PigAirwayPressure', 'PigArtPressure', 'PigCVP',
                                 'PLAID', 'Plane', 'PowerCons', 'ProximalPhalanxOutlineAgeGroup',
                                 'ProximalPhalanxOutlineCorrect', 'ProximalPhalanxTW', 'RefrigerationDevices',
                                 'Rock', 'ScreenType', 'SemgHandGenderCh2', 'SemgHandMovementCh2',
                                 'SemgHandSubjectCh2', 'ShakeGestureWiimoteZ', 'ShapeletSim', 'ShapesAll',
                                 'SmallKitchenAppliances', 'SmoothSubspace', 'SonyAIBORobotSurface1',
                                 'SonyAIBORobotSurface2', 'StarLightCurves', 'Strawberry', 'SwedishLeaf',
                                 'Symbols', 'SyntheticControl', 'ToeSegmentation1', 'ToeSegmentation2', 'Trace',
                                 'TwoLeadECG', 'TwoPatterns', 'UMD', 'UWaveGestureLibraryAll',
                                 'UWaveGestureLibraryX', 'UWaveGestureLibraryY', 'UWaveGestureLibraryZ',
                                 'Wafer', 'Wine', 'WordSynonyms', 'Worms', 'WormsTwoClass', 'Yoga']

HARD = ['InsectEPGSmallTrain','SemgHandMovementCh2', 'UWaveGestureLibraryY', 'UWaveGestureLibraryZ',
        'UWaveGestureLibraryAll', 'EOGVerticalSignal', 'StarLightCurves', 'Phoneme',
        'SemgHandSubjectCh2', 'ShakeGestureWiimoteZ', 'SmoothSubspace',
        'UMD', 'PigCVP','EthanolLevel','PowerCons',
        'PLAID', 'NonInvasiveFetalECGThorax1',
        'NonInvasiveFetalECGThorax2', 'Crop',
        'Rock', 'ElectricDevices', 'HandOutlines'
        ]

IMBA = ['Earthquakes', 'DistalPhalanxOutlineAgeGroup', 'ProximalPhalanxTW', 'ECG5000']
