UNIVARIATE_DATASET_NAMES = ['ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'Car', 'CBF',
                            'CinCECGTorso', 'Coffee',
                            'DiatomSizeReduction',
                            'DistalPhalanxOutlineAgeGroup', 'DistalPhalanxTW',
                            'Earthquakes', 'ECG200', 'ECGFiveDays', 'FaceFour',
                            'FacesUCR', 'Fish', 'GunPoint', 'Ham',
                            'Haptics', 'Herring', 'InlineSkate', 'ItalyPowerDemand',
                            'Lightning2', 'Lightning7', 'Mallat', 'Meat', 'MiddlePhalanxTW',
                            'MiddlePhalanxOutlineAgeGroup',
                            'MoteStrain', 'OliveOil',
                            'OSULeaf', 'Plane',
                            'ShapeletSim', 'SonyAIBORobotSurface1',
                            'SonyAIBORobotSurface2', 'Symbols',
                            'ToeSegmentation1', 'ToeSegmentation2', 'Trace', 'TwoLeadECG',
                            'Wine', 'Worms', 'WormsTwoClass']
LARGE = ['FiftyWords', 'Adiac', 'ChlorineConcentration', 'Computers', 'CricketX', 'CricketY', 'CricketZ',
         'DistalPhalanxOutlineCorrect',
         'ECG5000', 'ElectricDevices', 'FaceAll', 'FordA', 'FordB', 'HandOutlines', 'InsectWingbeatSound',
         'LargeKitchenAppliances', 'MedicalImages',
         'MiddlePhalanxOutlineCorrect', 'NonInvasiveFetalECGThorax1', 'NonInvasiveFetalECGThorax2',
         'PhalangesOutlinesCorrect', 'Phoneme', 'ProximalPhalanxOutlineAgeGroup',
         'ProximalPhalanxOutlineCorrect', 'ProximalPhalanxTW', 'RefrigerationDevices', 'ScreenType',
         'ShapesAll', 'SmallKitchenAppliances',
         'StarLightCurves', 'Strawberry', 'SwedishLeaf', 'SyntheticControl', 'TwoPatterns',
         'UWaveGestureLibraryAll', 'UWaveGestureLibraryX', 'UWaveGestureLibraryY',
         'UWaveGestureLibraryZ', 'Wafer', 'WordSynonyms', 'Yoga'
         ]

TOTAL85 = ['ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'Car', 'CBF',
           'CinCECGTorso', 'Coffee',
           'DiatomSizeReduction',
           'DistalPhalanxOutlineAgeGroup', 'DistalPhalanxTW',
           'Earthquakes', 'ECG200', 'ECGFiveDays', 'FaceFour',
           'FacesUCR', 'Fish', 'GunPoint', 'Ham',
           'Haptics', 'Herring', 'InlineSkate', 'ItalyPowerDemand',
           'Lightning2', 'Lightning7', 'Mallat', 'Meat', 'MiddlePhalanxTW',
           'MiddlePhalanxOutlineAgeGroup',
           'MoteStrain', 'OliveOil',
           'OSULeaf', 'Plane',
           'ShapeletSim', 'SonyAIBORobotSurface1',
           'SonyAIBORobotSurface2', 'Symbols',
           'ToeSegmentation1', 'ToeSegmentation2', 'Trace', 'TwoLeadECG',
           'Wine', 'Worms', 'WormsTwoClass', 'FiftyWords', 'Adiac', 'ChlorineConcentration', 'Computers', 'CricketX',
           'CricketY', 'CricketZ',
           'DistalPhalanxOutlineCorrect',
           'ECG5000', 'ElectricDevices', 'FaceAll', 'FordA', 'FordB', 'HandOutlines', 'InsectWingbeatSound',
           'LargeKitchenAppliances', 'MedicalImages',
           'MiddlePhalanxOutlineCorrect', 'NonInvasiveFetalECGThorax1', 'NonInvasiveFetalECGThorax2',
           'PhalangesOutlinesCorrect', 'Phoneme', 'ProximalPhalanxOutlineAgeGroup',
           'ProximalPhalanxOutlineCorrect', 'ProximalPhalanxTW', 'RefrigerationDevices', 'ScreenType',
           'ShapesAll', 'SmallKitchenAppliances',
           'StarLightCurves', 'Strawberry', 'SwedishLeaf', 'SyntheticControl', 'TwoPatterns',
           'UWaveGestureLibraryAll', 'UWaveGestureLibraryX', 'UWaveGestureLibraryY',
           'UWaveGestureLibraryZ', 'Wafer', 'WordSynonyms', 'Yoga']

TOTAL85 = ['ArrowHead', 'Beef', 'BeetleFly', 'BirdChicken', 'Car', 'CBF']